---
kind: pipeline
type: docker
name: publish docker

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

steps:
- name: publish
  image: plugins/docker
  settings:
    username: justmiles
    password: 
      from_secret: docker_password
    repo: justmiles/ecs-cli
    tags: latest
    squash: true
    auto_tag: true
    cache_from:
      - "justmiles/ecs-cli:latest"

---   
kind: pipeline
type: docker
name: publish docker slim

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

steps:
- name: publish
  image: plugins/docker
  settings:
    username: justmiles
    password: 
      from_secret: docker_password
    repo: justmiles/ecs-cli
    auto_tag_suffix: slim
    squash: true
    auto_tag: true
    cache_from:
      - "justmiles/ecs-cli:latest-slim"


## TODO add goreleaser pipeline for binary releases